import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import Navbar from "./_components/navbar/navbar";
import { Toaster } from "sonner";
import MySessionProvider from "@/mySessionProvider/mySessionProvider";
import SmallNavBar from "./_components/smallNavBar/smallNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  
});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* <i className="fa-solid fa-laptop"></i> */}

        <MySessionProvider>

        <Navbar/>
        <SmallNavBar/>
        {children}
        <Toaster/>
        </MySessionProvider>

      </body>
    </html>
  );
}
